// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "termsOfService": "http://swagger.io/terms/",
        "contact": {
            "name": "API Support",
            "url": "http://github.com/keif/image-optimizer/issues",
            "email": "support@example.com"
        },
        "license": {
            "name": "MIT",
            "url": "https://opensource.org/licenses/MIT"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/admin/cleanup-metrics": {
            "post": {
                "description": "Delete metrics data older than the specified retention period",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "admin"
                ],
                "summary": "Cleanup old metrics data",
                "parameters": [
                    {
                        "maximum": 365,
                        "minimum": 1,
                        "type": "integer",
                        "default": 30,
                        "description": "Retention period in days (default: 30)",
                        "name": "days",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Cleanup successful",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "Invalid parameters",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/api/keys": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Get a list of all API keys (excluding actual key values for security)",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "api-keys"
                ],
                "summary": "List all API keys",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/db.APIKey"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Create a new API key with a given name",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "api-keys"
                ],
                "summary": "Create a new API key",
                "parameters": [
                    {
                        "description": "API key name",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "object",
                            "properties": {
                                "name": {
                                    "type": "string"
                                }
                            }
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/db.APIKey"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/api/keys/{id}": {
            "delete": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Revoke an API key by its ID",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "api-keys"
                ],
                "summary": "Revoke an API key",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "API Key ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/batch-optimize": {
            "post": {
                "description": "Optimize multiple image files with the same quality, dimensions, and format settings",
                "consumes": [
                    "multipart/form-data"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "optimization"
                ],
                "summary": "Optimize multiple images in a single request",
                "parameters": [
                    {
                        "maximum": 100,
                        "minimum": 1,
                        "type": "integer",
                        "default": 80,
                        "description": "Quality level (1-100)",
                        "name": "quality",
                        "in": "query"
                    },
                    {
                        "minimum": 0,
                        "type": "integer",
                        "default": 0,
                        "description": "Target width in pixels (0 = no resize)",
                        "name": "width",
                        "in": "query"
                    },
                    {
                        "minimum": 0,
                        "type": "integer",
                        "default": 0,
                        "description": "Target height in pixels (0 = no resize)",
                        "name": "height",
                        "in": "query"
                    },
                    {
                        "enum": [
                            "jpeg",
                            "png",
                            "webp",
                            "gif",
                            "avif"
                        ],
                        "type": "string",
                        "description": "Target format",
                        "name": "format",
                        "in": "query"
                    },
                    {
                        "type": "file",
                        "description": "Image files to optimize (multiple files)",
                        "name": "images",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Batch optimization results",
                        "schema": {
                            "$ref": "#/definitions/routes.BatchOptimizeResponse"
                        }
                    },
                    "400": {
                        "description": "Invalid parameters or no files provided",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Batch processing error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/health": {
            "get": {
                "description": "Check API health status with version information",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "health"
                ],
                "summary": "Health check",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/routes.HealthResponse"
                        }
                    }
                }
            }
        },
        "/metrics/formats": {
            "get": {
                "description": "Get detailed statistics about format conversions",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "metrics"
                ],
                "summary": "Get format conversion statistics",
                "parameters": [
                    {
                        "maximum": 365,
                        "minimum": 1,
                        "type": "integer",
                        "default": 30,
                        "description": "Number of days to look back (default: 30)",
                        "name": "days",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "Invalid parameters",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/metrics/summary": {
            "get": {
                "description": "Get aggregated metrics for a specified time range",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "metrics"
                ],
                "summary": "Get metrics summary",
                "parameters": [
                    {
                        "maximum": 365,
                        "minimum": 1,
                        "type": "integer",
                        "default": 30,
                        "description": "Number of days to look back (default: 30)",
                        "name": "days",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/db.MetricsSummary"
                        }
                    },
                    "400": {
                        "description": "Invalid parameters",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/metrics/timeline": {
            "get": {
                "description": "Get time-series data for charting and trend analysis",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "metrics"
                ],
                "summary": "Get time-series metrics",
                "parameters": [
                    {
                        "maximum": 365,
                        "minimum": 1,
                        "type": "integer",
                        "default": 7,
                        "description": "Number of days to look back (default: 7)",
                        "name": "days",
                        "in": "query"
                    },
                    {
                        "enum": [
                            "hour",
                            "day"
                        ],
                        "type": "string",
                        "default": "hour",
                        "description": "Time interval: 'hour' or 'day' (default: 'hour')",
                        "name": "interval",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "Invalid parameters",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/optimize": {
            "post": {
                "description": "Optimize an image file or URL with custom quality, dimensions, and format",
                "consumes": [
                    "multipart/form-data"
                ],
                "produces": [
                    "application/json",
                    "image/jpeg",
                    "image/png",
                    "image/webp",
                    "image/gif",
                    "image/avif"
                ],
                "tags": [
                    "optimization"
                ],
                "summary": "Optimize an image",
                "parameters": [
                    {
                        "maximum": 100,
                        "minimum": 1,
                        "type": "integer",
                        "default": 80,
                        "description": "Quality level (1-100)",
                        "name": "quality",
                        "in": "query"
                    },
                    {
                        "minimum": 0,
                        "type": "integer",
                        "default": 0,
                        "description": "Target width in pixels (0 = no resize)",
                        "name": "width",
                        "in": "query"
                    },
                    {
                        "minimum": 0,
                        "type": "integer",
                        "default": 0,
                        "description": "Target height in pixels (0 = no resize)",
                        "name": "height",
                        "in": "query"
                    },
                    {
                        "enum": [
                            "jpeg",
                            "png",
                            "webp",
                            "gif",
                            "avif"
                        ],
                        "type": "string",
                        "description": "Target format",
                        "name": "format",
                        "in": "query"
                    },
                    {
                        "type": "boolean",
                        "default": false,
                        "description": "Return optimized image file instead of JSON metadata",
                        "name": "returnImage",
                        "in": "query"
                    },
                    {
                        "type": "boolean",
                        "default": false,
                        "description": "Enable lossless mode (perfect quality preservation)",
                        "name": "losslessMode",
                        "in": "query"
                    },
                    {
                        "enum": [
                            "nearest",
                            "bilinear",
                            "bicubic",
                            "nohalo",
                            "vsqbs",
                            "lanczos2",
                            "lanczos3"
                        ],
                        "type": "string",
                        "description": "Resizing interpolation algorithm",
                        "name": "interpolator",
                        "in": "query"
                    },
                    {
                        "type": "file",
                        "description": "Image file to optimize (multipart upload)",
                        "name": "image",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "description": "Image URL to fetch and optimize (alternative to file upload)",
                        "name": "url",
                        "in": "formData"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Optimized image file (when returnImage=true)",
                        "schema": {
                            "type": "file"
                        }
                    },
                    "400": {
                        "description": "Invalid parameters or file",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "403": {
                        "description": "URL domain not allowed",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "413": {
                        "description": "File too large (max 10MB)",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Image processing error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/optimize-spritesheet": {
            "post": {
                "description": "Accepts a spritesheet PNG and its XML, extracts frames, optionally deduplicates, and repacks optimally. Frame order is preserved by default to maintain animation sequences.",
                "consumes": [
                    "multipart/form-data"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "spritesheet"
                ],
                "summary": "Optimize an existing spritesheet",
                "parameters": [
                    {
                        "type": "file",
                        "description": "Spritesheet PNG image",
                        "name": "spritesheet",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "file",
                        "description": "Spritesheet XML (Sparrow format)",
                        "name": "xml",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "boolean",
                        "default": false,
                        "description": "Remove duplicate frames",
                        "name": "deduplicate",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "default": 2,
                        "description": "Padding between sprites in pixels",
                        "name": "padding",
                        "in": "query"
                    },
                    {
                        "type": "boolean",
                        "default": false,
                        "description": "Force power-of-2 dimensions. Dimensions capped at maxWidth/maxHeight.",
                        "name": "powerOfTwo",
                        "in": "query"
                    },
                    {
                        "type": "boolean",
                        "default": false,
                        "description": "Trim transparent pixels from sprites",
                        "name": "trimTransparency",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "default": 2048,
                        "description": "Maximum sheet width in pixels (256-12288)",
                        "name": "maxWidth",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "default": 2048,
                        "description": "Maximum sheet height in pixels (256-12288)",
                        "name": "maxHeight",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "default": "\"sparrow\"",
                        "description": "Comma-separated list of output formats: json,css,csv,xml,sparrow,texturepacker,cocos2d,unity,godot",
                        "name": "outputFormats",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "default": "\"spritesheet.png\"",
                        "description": "Image filename to reference in output formats (e.g., Sparrow XML imagePath attribute)",
                        "name": "imagePath",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "default": "\"optimal\"",
                        "description": "Packing algorithm mode: 'optimal' (best efficiency), 'smart' (60-80% efficiency, preserves frame order), 'preserve' (exact order, poorest efficiency). Recommended: use 'smart' for animations.",
                        "name": "packingMode",
                        "in": "query"
                    },
                    {
                        "type": "boolean",
                        "default": true,
                        "description": "DEPRECATED: Use packingMode='preserve' instead. Preserve original frame order (recommended for animations)",
                        "name": "preserveFrameOrder",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "default": "\"balanced\"",
                        "description": "PNG compression quality: fast, balanced, best",
                        "name": "compressionQuality",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Response includes warnings array if output size exceeds input or other packing issues detected",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/pack-sprites": {
            "post": {
                "description": "Accepts multiple image files and packs them into one or more optimized spritesheets using the MaxRects bin packing algorithm. Automatically splits into multiple sheets if needed. IMPORTANT: Each individual sprite must be ≤12288x12288 pixels (hard limit). Use autoResize=true to automatically resize oversized sprites - the response will include details of all resize operations.",
                "consumes": [
                    "multipart/form-data"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "spritesheet"
                ],
                "summary": "Pack multiple sprites into optimized spritesheets",
                "parameters": [
                    {
                        "type": "file",
                        "description": "Sprite images to pack (multiple files supported). Each sprite must be ≤12288x12288 pixels unless autoResize=true.",
                        "name": "images",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "default": 2,
                        "description": "Padding between sprites in pixels (0-32)",
                        "name": "padding",
                        "in": "query"
                    },
                    {
                        "type": "boolean",
                        "default": false,
                        "description": "Force power-of-2 dimensions (256, 512, 1024, etc.). Dimensions capped at maxWidth/maxHeight.",
                        "name": "powerOfTwo",
                        "in": "query"
                    },
                    {
                        "type": "boolean",
                        "default": false,
                        "description": "Trim transparent pixels from sprites",
                        "name": "trimTransparency",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "default": 2048,
                        "description": "Maximum sheet width in pixels (256-12288)",
                        "name": "maxWidth",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "default": 2048,
                        "description": "Maximum sheet height in pixels (256-12288)",
                        "name": "maxHeight",
                        "in": "query"
                    },
                    {
                        "type": "boolean",
                        "default": false,
                        "description": "Automatically resize sprites exceeding 12288x12288 to fit. Resize details returned in response.",
                        "name": "autoResize",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "default": "\"json\"",
                        "description": "Comma-separated list of output formats: json,css,csv,xml,sparrow,texturepacker,cocos2d,unity,godot",
                        "name": "outputFormats",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "default": "\"spritesheet.png\"",
                        "description": "Image filename to reference in output formats (e.g., Sparrow XML imagePath attribute)",
                        "name": "imagePath",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "default": "\"optimal\"",
                        "description": "Packing algorithm mode: 'optimal' (best efficiency), 'smart' (60-80% efficiency, preserves frame order), 'preserve' (exact order, poorest efficiency). Recommended: use 'smart' for animations.",
                        "name": "packingMode",
                        "in": "query"
                    },
                    {
                        "type": "boolean",
                        "default": false,
                        "description": "DEPRECATED: Use packingMode='preserve' instead. Preserve sprite upload order (disable height-based sorting for better animation support)",
                        "name": "preserveFrameOrder",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "default": "\"balanced\"",
                        "description": "PNG compression quality: fast, balanced, best",
                        "name": "compressionQuality",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Success response includes resizedSprites array if any sprites were auto-resized, and warnings array if output size exceeds input or other issues detected",
                        "schema": {
                            "$ref": "#/definitions/routes.PackSpritesResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/spritesheet/formats": {
            "get": {
                "description": "Returns a list of all supported output formats for spritesheet coordinate data",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "spritesheet"
                ],
                "summary": "Get supported spritesheet output formats",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "db.APIKey": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "key": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "revoked_at": {
                    "type": "string"
                }
            }
        },
        "db.MetricsSummary": {
            "type": "object",
            "properties": {
                "average_savings_percent": {
                    "type": "number"
                },
                "avg_processing_time_ms": {
                    "type": "number"
                },
                "failed_requests": {
                    "type": "integer"
                },
                "successful_requests": {
                    "type": "integer"
                },
                "total_bytes_optimized": {
                    "type": "integer"
                },
                "total_bytes_original": {
                    "type": "integer"
                },
                "total_bytes_saved": {
                    "type": "integer"
                },
                "total_requests": {
                    "type": "integer"
                }
            }
        },
        "routes.BatchImageResult": {
            "type": "object",
            "properties": {
                "error": {
                    "type": "string"
                },
                "filename": {
                    "type": "string"
                },
                "format": {
                    "type": "string"
                },
                "height": {
                    "type": "integer"
                },
                "optimizedSize": {
                    "type": "integer"
                },
                "originalSize": {
                    "type": "integer"
                },
                "savings": {
                    "type": "string"
                },
                "success": {
                    "type": "boolean"
                },
                "width": {
                    "type": "integer"
                }
            }
        },
        "routes.BatchOptimizeResponse": {
            "type": "object",
            "properties": {
                "results": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/routes.BatchImageResult"
                    }
                },
                "summary": {
                    "type": "object",
                    "properties": {
                        "failed": {
                            "type": "integer"
                        },
                        "processingTime": {
                            "type": "string"
                        },
                        "successful": {
                            "type": "integer"
                        },
                        "total": {
                            "type": "integer"
                        },
                        "totalOptimizedSize": {
                            "type": "integer"
                        },
                        "totalOriginalSize": {
                            "type": "integer"
                        },
                        "totalSavings": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "routes.HealthResponse": {
            "type": "object",
            "properties": {
                "commit": {
                    "type": "string",
                    "example": "c1a2b3c"
                },
                "status": {
                    "type": "string",
                    "example": "ok"
                },
                "timestamp": {
                    "type": "string",
                    "example": "2025-10-19T19:42:00Z"
                },
                "version": {
                    "type": "string",
                    "example": "v1.3.2"
                }
            }
        },
        "routes.OutputFileInfo": {
            "type": "object",
            "properties": {
                "content": {
                    "type": "string"
                },
                "extension": {
                    "type": "string"
                },
                "mimeType": {
                    "type": "string"
                }
            }
        },
        "routes.PackSpritesResponse": {
            "type": "object",
            "properties": {
                "metadata": {
                    "description": "Metadata for each sheet",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/routes.SheetMetadata"
                    }
                },
                "outputFiles": {
                    "description": "Format name -\u003e file info (content, extension, mime type)",
                    "type": "object",
                    "additionalProperties": {
                        "$ref": "#/definitions/routes.OutputFileInfo"
                    }
                },
                "resizedSprites": {
                    "description": "Info about auto-resized sprites",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/routes.ResizeInfo"
                    }
                },
                "sheets": {
                    "description": "Base64-encoded PNG images",
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "totalSprites": {
                    "type": "integer"
                },
                "warnings": {
                    "description": "Warnings about packing issues",
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                }
            }
        },
        "routes.ResizeInfo": {
            "type": "object",
            "properties": {
                "newHeight": {
                    "type": "integer"
                },
                "newWidth": {
                    "type": "integer"
                },
                "originalHeight": {
                    "type": "integer"
                },
                "originalWidth": {
                    "type": "integer"
                },
                "spriteName": {
                    "type": "string"
                }
            }
        },
        "routes.SheetMetadata": {
            "type": "object",
            "properties": {
                "efficiency": {
                    "type": "number"
                },
                "height": {
                    "type": "integer"
                },
                "index": {
                    "type": "integer"
                },
                "spriteCount": {
                    "type": "integer"
                },
                "width": {
                    "type": "integer"
                }
            }
        },
        "services.OptimizeResult": {
            "type": "object",
            "properties": {
                "alreadyOptimized": {
                    "description": "True if original was returned due to better compression",
                    "type": "boolean"
                },
                "colorSpace": {
                    "description": "Color space of the result (srgb, p3, etc)",
                    "type": "string"
                },
                "format": {
                    "type": "string"
                },
                "height": {
                    "type": "integer"
                },
                "message": {
                    "description": "Optional message about optimization",
                    "type": "string"
                },
                "optimizedSize": {
                    "type": "integer"
                },
                "originalColorSpace": {
                    "description": "Original image color space",
                    "type": "string"
                },
                "originalFormat": {
                    "description": "Original input format",
                    "type": "string"
                },
                "originalSize": {
                    "type": "integer"
                },
                "processingTime": {
                    "type": "string"
                },
                "savings": {
                    "type": "string"
                },
                "wideGamut": {
                    "description": "True if image uses colors beyond sRGB",
                    "type": "boolean"
                },
                "width": {
                    "type": "integer"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/",
	Schemes:          []string{"http", "https"},
	Title:            "Image Optimizer API",
	Description:      "High-performance image optimization service with format conversion, resizing, and quality adjustment",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
