# GitHub Sponsors & Donation Links
# These links will appear in the "Sponsor" button on your GitHub repo

github: keif
patreon: # Add your Patreon username if you have one
open_collective: # Add your Open Collective username if you have one
ko_fi: keif
tidelift: # Add your Tidelift platform-name/package-name
community_bridge: # Add your Community Bridge project name
liberapay: # Add your Liberapay username
issuehunt: # Add your IssueHunt username
lfx_crowdfunding: # Add your LFX Crowdfunding project name
polar: # Add your Polar username
buy_me_a_coffee: keif
custom: ['https://paypal.me/keif']
