version: 2

run:
  timeout: 5m
  tests: true
  skip-dirs:
    - vendor
    - testdata
    - docs

linters:
  enable:
    - errcheck
    - govet
    - staticcheck
    - unused
    - ineffassign
    - misspell
    - revive
    - gosec

linters-settings:
  errcheck:
    check-type-assertions: true

  govet:
    enable-all: true

  misspell:
    locale: US

  gosec:
    severity: medium
    confidence: medium

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - gosec
        - errcheck

output:
  format: colored-line-number
  print-issued-lines: true
  print-linter-name: true
  sort-results: true
