services:
  # API Service (Go + libvips)
  - type: web
    name: squish-api
    runtime: docker
    dockerfilePath: ./Dockerfile
    dockerContext: .
    envVars:
      - key: PORT
        value: 8080
      - key: CORS_ORIGINS
        value: https://keif.github.io,https://sosquishy.io,https://www.sosquishy.io,http://localhost:3000
      - key: DB_PATH
        value: /opt/render/project/data/api_keys.db
      - key: RATE_LIMIT_ENABLED
        value: true
      - key: RATE_LIMIT_MAX
        value: 100
      - key: RATE_LIMIT_WINDOW
        value: 1m
      - key: API_KEY_AUTH_ENABLED
        value: true
      - key: ALLOWED_DOMAINS
        value: cloudinary.com,imgur.com,unsplash.com,pexels.com
    healthCheckPath: /health
    disk:
      name: api-data
      mountPath: /opt/render/project/data
      sizeGB: 1
    plan: starter

  # Web Service (Next.js) - Now deployed to GitHub Pages
  # See .github/workflows/deploy-pages.yml for deployment configuration
  # Live at: https://sosquishy.io
