version: "2"

linters:
  enable:
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - unused
    - misspell
    - revive
    - gosec
  settings:
    gosec:
      excludes:
        - G204
        - G304
        - G101
    revive:
      rules:
        - name: exported
          disabled: true

formatters:
  enable:
    - gofmt
    - goimports

run:
  timeout: 5m
  tests: true
