version: 2

linters-settings:
  gosec:
    excludes:
      - G204
      - G304
      - G101
  revive:
    rules:
      - name: exported
        disabled: true

linters:
  enable:
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - unused
    - misspell
    - revive
    - gosec

formatters:
  enable:
    - gofmt
    - goimports

run:
  timeout: 5m
  tests: true

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - gosec
        - errcheck
